USE [Ashi]
GO

/****** Object:  Table [dbo].[BookReviewStatus]    Script Date: 28/02/2020 3:34:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SportType](
	[SportTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_SportType] PRIMARY KEY CLUSTERED 
(
	[SportTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


